"""Se agrega marca

Revision ID: 0af9e501f65c
Revises: 4312897d689f
Create Date: 2022-11-17 09:57:21.678247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af9e501f65c'
down_revision = '4312897d689f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    #HINT
    '''
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lines', sa.Column('id_brand', sa.String(length=45), nullable=True))
    op.create_foreign_key(None, 'lines', 'brands', ['id_brand'], ['id_runt'])
    op.create_index(op.f('ix_vehicle_id'), 'vehicle', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_name'), 'vehicle', ['name'], unique=True)
    # ### end Alembic commands ###
    '''
    pass

def downgrade() -> None:
    '''
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_name'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_column('lines', 'id_brand')
    # ### end Alembic commands ###
    '''
    pass