"""lines

Revision ID: 147427a42185
Revises: 81700da9a789
Create Date: 2022-11-15 19:54:40.934737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147427a42185'
down_revision = '81700da9a789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lines',
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lines')
    # ### end Alembic commands ###
