"""Agregar ciudad

Revision ID: 1cfa4ef97795
Revises: b9726613c0aa
Create Date: 2022-10-24 18:43:56.207686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cfa4ef97795'
down_revision = 'b9726613c0aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('country', sa.String(length=45), nullable=True),
    sa.Column('cod_name', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('cod_name')
    )
    op.create_index(op.f('ix_cities_cod_name'), 'cities', ['cod_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_cod_name'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
