"""actionmodel

Revision ID: 2714d007c2b1
Revises: 1cfa4ef97795
Create Date: 2022-10-26 21:33:02.213847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2714d007c2b1'
down_revision = '1cfa4ef97795'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Actions',
    sa.Column('description', sa.String(length=45), nullable=False),
    sa.Column('medida', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('description')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Actions')
    # ### end Alembic commands ###
