"""actionmodel

Revision ID: 371ebad4c4fd
Revises: 147427a42185
Create Date: 2022-11-15 20:31:21.258466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '371ebad4c4fd'
down_revision = '147427a42185'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #Esta tabla no se estaba creando
    #op.drop_table('Type_ful')
    op.create_table('type_fuel',
                    sa.Column('name', mysql.VARCHAR(length=45), nullable=False),
                    sa.PrimaryKeyConstraint('name'),
                    mysql_default_charset='latin1',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Type_fuel', sa.Column('name', mysql.VARCHAR(length=45), nullable=False))
    op.drop_column('Type_fuel', 'description')
    op.create_table('Type_ful',
    sa.Column('name', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
