"""Renovacion de modelos 

Revision ID: 4312897d689f
Revises: 
Create Date: 2022-11-16 21:07:51.987175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4312897d689f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id_runt', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id_runt')
    )
    op.create_table('cities',
    sa.Column('country', sa.String(length=45), nullable=True),
    sa.Column('cod_name', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('cod_name')
    )
    op.create_index(op.f('ix_cities_cod_name'), 'cities', ['cod_name'], unique=False)
    op.create_table('lines',
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('type_fuel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('last_name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_name'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('type_fuel')
    op.drop_table('lines')
    op.drop_index(op.f('ix_cities_cod_name'), table_name='cities')
    op.drop_table('cities')
    op.drop_table('brands')
    # ### end Alembic commands ###
