"""se agregan propiedades

Revision ID: 4ef85cd702e6
Revises: 371ebad4c4fd
Create Date: 2022-11-15 22:55:37.297756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ef85cd702e6'
down_revision = '371ebad4c4fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Actions')
    op.alter_column('brands', 'description',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.add_column('type_fuel', sa.Column('description', sa.String(length=45), nullable=False))
    op.drop_column('type_fuel', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_fuel', sa.Column('name', mysql.VARCHAR(length=45), nullable=False))
    op.drop_column('type_fuel', 'description')
    op.alter_column('brands', 'description',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.create_table('Actions',
    sa.Column('description', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('medida', mysql.VARCHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('description'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
