"""actionmodel

Revision ID: 81700da9a789
Revises: 2714d007c2b1
Create Date: 2022-10-31 21:57:31.122261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81700da9a789'
down_revision = '2714d007c2b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Brands', sa.Column('id_runt', sa.Integer(), nullable=False))
    op.drop_column('Brands', 'medida')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Brands', sa.Column('medida', mysql.VARCHAR(length=1), nullable=True))
    op.drop_column('Brands', 'id_runt')
    # ### end Alembic commands ###
