"""add field list

Revision ID: 876400428e5e
Revises: 22d80b19dde4
Create Date: 2022-12-01 20:22:42.947723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876400428e5e'
down_revision = '22d80b19dde4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lines', sa.Column('id_brand', sa.String(length=45), nullable=True))
    op.create_foreign_key(None, 'lines', 'brands', ['id_brand'], ['id_runt'])
    op.create_index(op.f('ix_vehicle_id'), 'vehicle', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_name'), 'vehicle', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_name'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_column('lines', 'id_brand')
    # ### end Alembic commands ###
